# Site
name: 'lowzhao'
description: 'Lowzhao Blog, Medium like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
fa_icons: 'assets/icons/font-mfizz-2.4.1/font-mfizz.css'
baseurl: ''
disqus: 'lowzhao'
email: 'lowzhao@gmail.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

show_jumbotron: false
showPageHeader: false

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    eugene:
      name:           Eugene Low
      site:           https://lowzhao.com
      avatar:         assets/images/eugene.jpg
      bio:            "Hi, I am Eugene!"
      email:          lowzhao@gmail.com
      twitter:        https://twitter.com/ZhiHaoLow
      facebook:       https://www.facebook.com/zhihao.low.3
      linkedin:       https://www.linkedin.com/in/lowzhao/
      facebook:       https://github.com/lowzhao
      cv:             assets/docs/CV.pdf
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: eugene
      avatar: assets/images/eugene.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]